require('nvim-treesitter.configs').setup {
  ensure_installed = {
    'bash',
    'css',
    'dockerfile',
    'html',
    'javascript',
    'json',
    'jsonc',
    'lua',
    'markdown',
    'markdown_inline',
    'rust',
    'scss',
    'sql',
    'toml',
    'typescript',
    'vue',
    'xml',
    'yaml',
  },
  sync_install = false,
  auto_install = true,
  highlight = { enable = true },
}
