require 'mslawins.options'
require 'mslawins.keymaps'
require 'mslawins.paq'
require 'mslawins.colorscheme'

require 'mslawins.plugins.barbar'
require 'mslawins.plugins.ChatGPT'
require 'mslawins.plugins.gitblame'
require 'mslawins.plugins.glow'
require 'mslawins.plugins.harpoon'
require 'mslawins.plugins.lspsaga'
require 'mslawins.plugins.lualine'
require 'mslawins.plugins.mason'
require 'mslawins.plugins.nvim-autopairs'
require 'mslawins.plugins.nvim-tree'
require 'mslawins.plugins.nvim_comment'
require 'mslawins.plugins.nvim-colorizer'
require 'mslawins.plugins.telescope'
require 'mslawins.plugins.todo-comments'
require 'mslawins.plugins.treesitter'
require 'mslawins.plugins.vim-matchtag'
require 'mslawins.plugins.vim-rooter'

require 'mslawins.cmp'
require 'mslawins.null-ls'
